export const PENDING_GET_MOVIES = "PENDING_GET_MOVIES";
export const GET_MOVIES = "GET_MOVIES";
export const ERROR_GET_MOVIES = "ERROR_GET_MOVIES";

export const PENDING_ADD_MOVIES = "PENDING_ADD_MOVIES";
export const ADD_MOVIES = "ADD_MOVIES";
export const ERROR_ADD_MOVIES = "ERROR_ADD_MOVIES";

export const PENDING_DELETE_MOVIES = "PENDING_DELETE_MOVIES";
export const DELETE_MOVIES = "DELETE_MOVIES";
export const ERROR_DELETE_MOVIES = "ERROR_DELETE_MOVIES";

export const PENDING_UPDATE_MOVIES = "PENDING_UPDATE_MOVIES";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const ERROR_UPDATE_MOVIES = "ERROR_UPDATE_MOVIES";

export const PENDING_GET_MOVIE_BY_ID = "PENDING_GET_MOVIE_BY_ID";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const ERROR_GET_MOVIE_BY_ID = "ERROR_GET_MOVIE_BY_ID";
